---
- name: "MongoDB: Import public key"
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: 4B7C549A058F8B6B

- name: "MongoDB: Add repository"
  apt_repository:
    repo: "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.2 multiverse"
    filename: "/etc/apt/sources.list.d/mongodb-org-4.2.list"
    update_cache: yes
  tags: install

- name: "MongoDB: Install"
  apt:
    name: mongodb-org
    update_cache: yes
  tags: install