---
# tasks file for app
- name: Show info about the env this host belongs to
  debug:
    msg: "This host is in {{ env }} environment!!!"

- name: Add config for DB connection
  template:
    src: db_config.j2
    dest: /home/appuser/db_config
  tags: app-tag

- name: "Reddit App: clone application"
  git:
    repo: https://github.com/Artemmkin/reddit.git
    dest: ~/reddit
    version: monolith
    force: yes
  notify: restart puma
  tags: app-tag

- name: "Reddit App: install bundler"
  bundler:
    chdir: ~/reddit
  tags: app-tag

- name: "Reddit App: Set app as service"
  copy:
    src: puma.service
    dest: /etc/systemd/system/puma.service
  become: yes
  tags: app-tag