# Update cache
- name: "Update cache"
  hosts: all
  gather_facts: no
  become: yes
  
  tasks:
  - name: "Update cache"
    apt:
      update_cache: yes
      force_apt_get: yes

# Setup and configure ruby things for reddit app
- name: "Reddit App: Configure app environment"
  hosts: reddit-app
  gather_facts: no
  
  tasks:
  - name: "Reddit App: Install ruby and rubygems and required packages"
    apt:
      name:
      - ruby-full
      - ruby-dev
      - build-essential

  - name: "Reddit App: Install Ruby bundler"
    gem:
      name: bundler
      user_install: no

# Setup and configure mongodb for reddit app
- name: "MongoDB: Install mongodb"
  hosts: all
  gather_facts: no
  become: yes

  tasks:
      
  - name: "MongoDB: Install"
    apt:
      name: mongodb
      
  - name: "MongoDB: Running state"
    service:
      name: mongodb
      state: started
      enabled: yes

# Deploy reddit app
- name: "Reddit App: Deploy application"
  hosts: all
  gather_facts: no
  become: no
  vars:
    update: no

  tasks:
  - name: "Reddit App: clone application"
    git:
      repo: https://github.com/Artemmkin/reddit.git
      dest: ~/reddit
      update: no
      
  - name: "Reddit App: update application"
    git:
      dest: ~/reddit
      update: yes
      clone: no
    when: update == 'yes'
      
  - name: "Reddit App: install dependencies"
    bundler:
      gemfile: ~/reddit/Gemfile
      
  - name: "Reddit App: Set app as service"
    copy:
      src: ~/Vadim/gcp-configuration/terraform/files/puma.service
      dest: /etc/systemd/system/puma.service
    become: yes
      
  - name: "Reddit App: Start service"
    systemd:
      name: puma
      state: restarted
      enabled: yes
    become: yes