#---
#dependency:
#  name: galaxy
#driver:
#  name: vagrant
#platforms:
#  - name: instance
#provisioner:
#  name: ansible
#verifier:
#  name: ansible
---
driver:
  name: vagrant
  provider:
    name: virtualbox
lint: yamllint
platforms:
  - name: instance
    box: ubuntu/xenial64
#    provider_raw_config_args:
#      - "customize [ 'modifyvm', :id, '--uartmode1', 'disconnected' ]"
provisioner:
  name: ansible
  lint: ansible-lint
